Script                         Status     Output                                            
==========================================================================================
calibrate_gaze.py              Failed     Traceback (most recent call last):
  File "calibrate_gaze.py", line 5, in <module>
    from gaze_tracking import GazeTracking
ModuleNotFoundError: No module named 'gaze_tracking'

compute_transformation_matrix.py Passed     Transformation matrix:
[[9.99999968e-04 0.00000000e+00 4.65661279e-09]
 [0.00000000e+00 9.99999968e-04 4.65661260e-09]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
test_compute_transformation_matrix passed.

create_heatmap.py              Passed     test_create_heatmap passed.

display_heatmap.py             Failed     [ WARN:0@0.563] global loadsave.cpp:268 cv::findDecoder imread_('AdImages\PHOTO-2025-03-02-09-10-01.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "display_heatmap.py", line 34, in <module>
    test_display_heatmap()
  File "display_heatmap.py", line 25, in test_display_heatmap
    display_heatmap(heatmap, ad_path)
  File "display_heatmap.py", line 12, in display_heatmap
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


get_screen_resolution.py       Passed     test_get_screen_resolution passed.

map_gaze_to_grid.py            Passed     test_map_gaze_to_grid passed.

show_ad.py                     Failed     Traceback (most recent call last):
  File "show_ad.py", line 5, in <module>
    from gaze_tracking import GazeTracking
ModuleNotFoundError: No module named 'gaze_tracking'

update_heatmap.py              Passed     test_update_heatmap passed.